version: '3.8'
services:
  api:
    build: .
    container_name: sandbox-api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '3000:3000'
    depends_on:
      - db
      - redis
    volumes:
      - ./:/usr/src/app
    command: npm run start:dev

  db:
    image: postgres:15
    container_name: sandbox-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: sandbox
      POSTGRES_PASSWORD: sandboxpass
      POSTGRES_DB: sandbox
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: sandbox-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata: 